name: Build Trailer Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Отримуємо повну історію для уникнення конфліктів

      - name: Concatenate JavaScript files
        run: |
          cat src/utils.js src/api.js src/trailer.js src/line.js src/component-main.js src/component-full.js src/plugin.js src/index.js > test_youtube.js

      - name: Verify output
        run: |
          if [ -s test_youtube.js ]; then
            echo "Build successful: test_youtube.js created"
          else
            echo "Build failed: test_youtube.js is empty or not created"
            exit 1
          fi

      - name: Commit test_youtube.js before rebase
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add test_youtube.js
          git commit -m "Temporary commit for test_youtube.js" || echo "No changes to commit"

      - name: Pull and push changes
        run: |
          git pull --rebase origin main
          git add test_youtube.js
          git commit -m "Update test_youtube.js from build" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test_youtube
          path: test_youtube.js
          retention-days: 7
