name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Pull latest changes
      run: git pull --rebase origin main

    - name: Concatenate JS files
      run: |
        echo "(function() {'use strict';" > build/upcoming.js
        cat src/utils.js src/api.js src/component.js src/init.js >> build/upcoming.js
        echo "})();" >> build/upcoming.js

    - name: Commit changes
      run: |
        git add build/upcoming.js
        git commit -m "Update upcoming.js" || echo "No changes to commit"

    - name: Push changes
      run: git push origin main

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
