name: Build Upcoming Plugin
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Concatenate JS files with IIFE wrapper
        run: |
          mkdir -p build
          echo "(function () {" > build/upcoming.js
          echo "'use strict';" >> build/upcoming.js
          cat src/utils.js >> build/upcoming.js
          cat src/api.js >> build/upcoming.js
          cat src/components.js >> build/upcoming.js
          cat src/init.js >> build/upcoming.js
          echo "})();" >> build/upcoming.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
