name: Build and Deploy t2.js

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Перевіряємо код
      - name: Checkout code
        uses: actions/checkout@v4

      # Створюємо dist/t2.js за допомогою cat
      - name: Build t2.js
        run: |
          mkdir -p dist
          echo "(function () {" > dist/t2.js
          echo "    'use strict';" >> dist/t2.js
          cat t2/utils.js t2/api.js t2/trailer.js t2/line.js t2/component.js t2/index.js >> dist/t2.js
          echo "})();" >> dist/t2.js

      # Комітимо dist/t2.js у гілку main
      - name: Commit dist/t2.js
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add dist/t2.js
          git commit -m "Update dist/t2.js" || echo "No changes to commit"
          git push origin main

      # Налаштування GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Публікуємо dist/ на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Deploy artifact
        uses: actions/deploy-pages@v4
