name: Build and Deploy t2.js

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Перевіряємо код із репозиторію
      - name: Checkout code
        uses: actions/checkout@v4

      # Створюємо dist/t2.js за допомогою cat
      - name: Build t2.js
        run: |
          mkdir -p dist
          echo "(function () {" > dist/t2.js
          echo "    'use strict';" >> dist/t2.js
          cat t2/utils.js t2/api.js t2/trailer.js t2/line.js t2/component.js t2/index.js >> dist/t2.js
          echo "})();" >> dist/t2.js

      # Публікуємо dist/ на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
